---
llama_server_install_dir: /opt/llama-server
llama_server_model_dir: /var/lib/llama-server/models
llama_server_api_key_path: /etc/llama-server/api-keys

llama_server_context_size: 65536
llama_server_context_fallbacks:
  - 32768
  - 16384
llama_server_parallel: 1
llama_server_backend: intel

llama_server_intel_image: >-
  ghcr.io/ggml-org/llama.cpp:server-intel@sha256:58b3ad3bcbd805ef4094b1daaed8c9df4db9fc02aded25727883d5ad512cabda
llama_server_vulkan_image: >-
  ghcr.io/ggml-org/llama.cpp:server-vulkan@sha256:71da21f3ca71dba2150c729b98cdf76a827747221af65ac36219d35ab7cb6ab7

llama_server_model_revision: 4ca720788d1e01f1bff70c033e0d0028fd02e502
llama_server_model_file: Qwen3.8-27B-UD-Q4_K_M.gguf
llama_server_model_checksum: sha256:322e194ff79741c7baa497c240f677f54b201b0efab44ca8e50f122b39123482
llama_server_mmproj_file: mmproj-F16.gguf
llama_server_mmproj_checksum: sha256:cbb841a9ee0636b2ec172f5bb8df2ea8dfeb01e90fe7c6126581d662a0b4e43e
