---
all:
  children:
    ubuntu:
      hosts:
        ubuntu-gpu:
          ansible_host: 10.132.247.37
          ansible_user: "{{ vault_ubuntu_gpu_username }}"
          ansible_become_password: "{{ vault_ubuntu_gpu_become_password }}"

