---
- name: Remove conflicting container packages
  ansible.builtin.apt:
    name:
      - containerd
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - runc
    state: absent
  become: true

- name: Create APT keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Install Docker repository key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true

- name: Configure Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: [stable]
    architectures: [amd64]
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
  become: true

- name: Install Docker Engine and Compose
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: Enable Docker service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started
  become: true

- name: Add managed user to docker group
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true
  become: true

