---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install base packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - jq
      - python3-debian
    state: present
  become: true
